name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm install
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Run Playwright tests
      run: npx playwright test --config=playwright.service.config.ts --workers=20
    - name: Upload Playwright report to static site (run-specific folder)
      if: always()
      run: |
        if [ -d playwright-report ]; then
          RUN_ID_DIR="run-${GITHUB_RUN_ID}"
          # Ensure an index.html inside report (copy fallback)
            if [ ! -f playwright-report/index.html ] && [ -f playwright-report/report.html ]; then
              cp playwright-report/report.html playwright-report/index.html
            fi
          az storage blob upload-batch \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            -s playwright-report \
            -d "\$web/$RUN_ID_DIR" \
            --overwrite \
            --auth-mode login
          FULL_URL="https://${AZURE_STORAGE_ACCOUNT}.z13.web.core.windows.net/${RUN_ID_DIR}/index.html"
          echo "Playwright Report URL: ${FULL_URL}" >> $GITHUB_STEP_SUMMARY
          echo "REPORT_URL=${FULL_URL}" >> $GITHUB_ENV
          echo "Report uploaded to ${FULL_URL}"
        else
          echo "No playwright-report directory present" >> $GITHUB_STEP_SUMMARY
        fi
      env:
        AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
